#!/usr/bin/lua

local site = require 'gluon.site'

local uci = require('simple-uci').cursor()

if site.offline_ssid ~= nil then
	local site_enabled = site.offline_ssid.enabled() or '1'

	uci:section('offline-ssid', 'settings', 'settings', {
		enabled           = uci:get('offline-ssid', 'settings', 'enabled') or site_enabled,
		switch_timeframe  = site.offline_ssid.switch_timeframe() or '30',
		first             = site.offline_ssid.first() or '5',
		prefix            = site.offline_ssid.prefix() or 'FF_Offline_',
		suffix            = site.offline_ssid.suffix() or 'nodename',
		tq_limit_enabled  = site.offline_ssid.tq_limit_enabled() or false,
		tq_limit_max      = site.offline_ssid.tq_limit_max() or 45,
		tq_limit_min      = site.offline_ssid.tq_limit_min() or 35,
	})
	uci:save('offline-ssid')
end
